apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: pdocklab/kub-kind-tasks:latest
          env:
            - name: AUTH_ADDRESS
              # value: "10.107.50.99"
              value: "auth-service.default"
              # value: "auth-service.myapp"
            - name: TASKS_FOLDER
              value: tasks